Added initial support for automatic paramater lookups! Very close now to being ready for a 1.0 release.
This is now what I would call a "minimally viable product", but
I still want to add a few things before the 1.0.0 release.

diff --git a/bin/glowing-octo-ninja b/bin/glowing-octo-ninja
--- a/bin/glowing-octo-ninja
+++ b/bin/glowing-octo-ninja
@@ -89,100 +89,109 @@ if [ $# -gt 0 ]; then
   done
 fi
 
-##Need the configdir
-#declare -r CONFIGDIR="$("${PUPPET_BIN}" config print confdir 2> /dev/null)"
-#
-## Need to determine if we are using directory environments or config eviron
-#declare -r ENVIRONMENTPATH="$("${PUPPET_BIN}" config print environmentpath 2> /dev/null)"
-#declare -r BASEMODULEPATH="$("${PUPPET_BIN}" config print basemodulepath 2> /dev/null)"
-#
-## Assume directory environments are being used; we'll check for an empty $ENVIRONMENTPATH next and reset as-needed.
-#mod_ep="${ENVIRONMENTPATH}"
-#mod_bmp="${BASEMODULEPATH}"
-#[[ ${ENVIRONMENTPATH} =~ '$confdir' ]] && mod_ep="${ENVIRONMENTPATH/'$confdir'/${CONFIGDIR}}"
-#[[ ${BASEMODULEPATH} =~ '$confdir' ]]  && mod_bmp="${BASEMODULEPATH/'$confdir'/${CONFIGDIR}}"
-#modulelist="${mod_ep} ${mod_bmp}"
-## -- This is our check for config directories in play, rather than directory environments.
-#if [ "${ENVIRONMENTPATH}" == '' ]; then #config directories are in play
-#  modulelist="$("${PUPPET_BIN}" config print modulepath | sed -e "s/:/ /g")"       # Assume static config directory (overwriting from above).
-#  if grep -qe  "modulepath.*[$][::]\?environment" "${CONFIGDIR}/puppet.conf"; then # Dynamic Environments, reset modulelist for compilation below.
-#    modulelist=""
-#    for m in $(grep -P  '^[\s]*modulepath' "${CONFIGDIR}/puppet.conf" | cut -d'=' -f2 | awk 'BEGIN {RS = ":"} ; {print $0}') ; do
-#      if grep -P '\$(::)?environment' <<<"${m}" | grep -Po '^[$|/][a-zA-Z/]*'; then
-#        if [[ "${m}" =~ '$confdir' ]]; then
-#          kladsjhfiladhfklasjdfghldksj="$(echo ${m} | grep -Po '^[$|/][a-zA-Z/]*')"
-#          modulelist="${modulelist} ${kladsjhfiladhfklasjdfghldksj/\$confdir/${CONFIGDIR}}"
-#        else
-#          modulelist="${modulelist} $(echo ${m} | grep -Po '^[$|/][a-zA-Z/]*')"
-#        fi
-#      else
-#        if [[ "${m}" =~ '$confdir' ]]; then
-#          modulelist="${modulelist} ${m/\$confdir/${CONFIGDIR}}"
-#        else
-#          modulelist="${modulelist} ${m}"
-#        fi
-#      fi
-#    done
-#  fi
-#fi
-#
-#declare -r HIERADIR="$("${PUPPET_BIN}" config print hiera_config 2> /dev/null)"
-#declare -r CERTLIST_RAW="$("${PUPPET_BIN}" cert list --all 2> /dev/null | grep -Pho "(?<=\+ \")([a-z0-9-_.]+)")"
-#declare    CERTLIST=""
-#declare -r VARLIST="$(grep -Pho "(?<=%\{)(.+)(?=\})" ${HIERADIR})"
-#Still need to account for automatic parameter lookups
-declare -r HIERA_P_LIST="$(find / -name \"*.pp\" -exec awk '/^class [a-zA-Z]/ {mypath = FILENAME; if ($2 ~ /\(/ || $3 == \"(\") { do if (getline) { if ($1 !~ /\)/ && $1 ~ /^\$/) { myparam = $1; sub( /^\/.*\/modules\//, \"\", mypath); sub( /\/manifests\//, \"/\", mypath ); sub( /\.pp/, \"\", mypath); if ( mypath ~ /\/init/ ) {sub( /\/init/, \"\", mypath)}gsub( /\//, \"::\", mypath); sub(/\$/, \"\", myparam); sub( /,.*/, \"\", myparam); print (\"$\" mypath \"::\" myparam)}} while($0 !~ /\)/)}}' {} \;)"
+#Need the configdir
+declare -r CONFIGDIR="$("${PUPPET_BIN}" config print confdir 2> /dev/null)"
 
-echo "HIERA_P_LIST is '${HIERA_P_LIST}'"
+# Need to determine if we are using directory environments or config eviron
+declare -r ENVIRONMENTPATH="$("${PUPPET_BIN}" config print environmentpath 2> /dev/null)"
+declare -r BASEMODULEPATH="$("${PUPPET_BIN}" config print basemodulepath 2> /dev/null)"
 
-#declare -r HIERA_LIST="$(for h in ${modulelist}; do grep -PIRho "(?<=hiera\(['|\"|$])([^'|^\"|^,|^\)]+)" ${h} | sort -u; done)"
-#declare -r HIERA_A_LIST="$(for ha in ${modulelist}; do grep -PIRho "(?<=hiera_array\(['|\"|$])([^'|^\"|^,|^\)]+)" ${ha} | sort -u; done)"
-#declare -r HIERA_H_LIST="$(for hh in ${modulelist}; do grep -PIRho "(?<=hiera_hash\(['|\"|$])([^'|^\"|^,|^\)]+)" ${hh} | sort -u; done)"
-#declare -r HIERA_BASE_OPTS="-c ${HIERADIR}"
-#declare -r HIERA="$(which hiera)"
-#declare -r HIERA_BASE_CMD="${HIERA} ${HIERA_BASE_OPTS}"
-#declare    HIERA_CMD="${HIERA_BASE_CMD} ${HIERA_EXTRA_OPTS}"
-#
-#for cert in ${CERTLIST_RAW}; do [ "${cert}" == "${cert/pe-internal-/}" ] && CERTLIST="${CERTLIST} ${cert}" ; done
-#
-#case "${fact_src}" in
-#  'yaml' )
-#    for node in ${CERTLIST}; do
-#      if [ ! -f "${node}.yaml" ] ; then echo "Warning, could not find ${node}.yaml.  Skipping." ; continue 1 ; fi
-#      echo "Looking up hiera() call values for ${node}."
-#      for ch in ${HIERA_LIST} ; do ${HIERA_CMD} "${FILE_BASE}/${node}.yaml" "${ch}"; done
-#      echo "Looking up hiera_array() call values for ${node}."
-#      for cha in ${HIERA_A_LIST} ; do ${HIERA_CMD} "${FILE_BASE}/${node}.yaml" -a "${cha}"; done
-#      echo "Looking up hiera_hash() call values for ${node}."
-#      for chh in ${HIERA_H_LIST} ; do ${HIERA_BASE_CMD} "${FILE_BASE}/${node}.yaml" -h "${chh}"; done
-#    done
-#    ;;
-#  'json' )
-#    for node in ${CERTLIST}; do
-#      if [ ! -f "${node}.json" ] ; then echo "Warning, could not find ${node}.json. Skipping." ; continue 1 ; fi
-#      echo "Looking up hiera() call values for ${node}."
-#      for ch in ${HIERA_LIST} ; do ${HIERA_CMD} "${FILE_BASE}/${node}.json" "${ch}"; done
-#      echo "Looking up hiera_array() call values for ${node}."
-#      for cha in ${HIERA_A_LIST} ; do ${HIERA__CMD} "${FILE_BASE}/${node}.json" -a "${cha}"; done
-#      echo "Looking up hiera_hash() call values for ${node}."
-#      for chh in ${HIERA_H_LIST} ; do ${HIERA_BASE_CMD} "${FILE_BASE}/${node}.json" -h "${chh}"; done
-#    done
-#    ;;
-#  'user' )
-#    HIERA_CMD="sudo -u ${USER_NAME} ${HIERA} ${hiera_extra_opts} ${HIERA_BASE_OPTS}"
-#    grep -qF "${USER_NAME}" /etc/passwd || fail_sauce "User '${USER_NAME}' not found. Please check spelling. Exiting."
-#    for node in ${CERTLIST}; do
-#      echo "Looking up hiera() call values for ${node}."
-#      for ch in ${HIERA_LIST} ; do echo "${ch} is $( ${HIERA_CMD} -m "${node}" "${ch}")"; done
-#      echo "Looking up hiera_array() call values for ${node}."
-#      for cha in ${HIERA_A_LIST} ; do echo "${cha} is $( ${HIERA_CMD} -a -m "${node}" "${cha}")"; done
-#      echo "Looking up hiera_hash() call values for ${node}."
-#      for chh in ${HIERA_H_LIST} ; do echo "${chh} is $( ${HIERA_CMD} -h -m "${node}" "${chh}")"; done
-#    done
-#    ;;
-#  * )
-#    fail_sauce "Unknown fact source '${fact_src}'. Exiting."
-#    ;;
-#esac
-#
+# Assume directory environments are being used; we'll check for an empty $ENVIRONMENTPATH next and reset as-needed.
+mod_ep="${ENVIRONMENTPATH}"
+mod_bmp="${BASEMODULEPATH}"
+[[ ${ENVIRONMENTPATH} =~ '$confdir' ]] && mod_ep="${ENVIRONMENTPATH/'$confdir'/${CONFIGDIR}}"
+[[ ${BASEMODULEPATH} =~ '$confdir' ]]  && mod_bmp="${BASEMODULEPATH/'$confdir'/${CONFIGDIR}}"
+modulelist="${mod_ep} ${mod_bmp}"
+# -- This is our check for config directories in play, rather than directory environments.
+if [ "${ENVIRONMENTPATH}" == '' ]; then #config directories are in play
+  modulelist="$("${PUPPET_BIN}" config print modulepath | sed -e "s/:/ /g")"       # Assume static config directory (overwriting from above).
+  if grep -qe  "modulepath.*[$][::]\?environment" "${CONFIGDIR}/puppet.conf"; then # Dynamic Environments, reset modulelist for compilation below.
+    modulelist=""
+    for m in $(grep -P  '^[\s]*modulepath' "${CONFIGDIR}/puppet.conf" | cut -d'=' -f2 | awk 'BEGIN {RS = ":"} ; {print $0}') ; do
+      if grep -P '\$(::)?environment' <<<"${m}" | grep -Po '^[$|/][a-zA-Z/]*'; then
+        if [[ "${m}" =~ '$confdir' ]]; then
+          kladsjhfiladhfklasjdfghldksj="$(echo ${m} | grep -Po '^[$|/][a-zA-Z/]*')"
+          modulelist="${modulelist} ${kladsjhfiladhfklasjdfghldksj/\$confdir/${CONFIGDIR}}"
+        else
+          modulelist="${modulelist} $(echo ${m} | grep -Po '^[$|/][a-zA-Z/]*')"
+        fi
+      else
+        if [[ "${m}" =~ '$confdir' ]]; then
+          modulelist="${modulelist} ${m/\$confdir/${CONFIGDIR}}"
+        else
+          modulelist="${modulelist} ${m}"
+        fi
+      fi
+    done
+  fi
+fi
+
+declare -r HIERADIR="$("${PUPPET_BIN}" config print hiera_config 2> /dev/null)"
+declare -r CERTLIST_RAW="$("${PUPPET_BIN}" cert list --all 2> /dev/null | grep -Pho "(?<=\+ \")([a-z0-9-_.]+)")"
+declare    CERTLIST=""
+declare -r VARLIST="$(grep -Pho "(?<=%\{)(.+)(?=\})" ${HIERADIR})"
+
+px=0
+for p in $(find / -name "*.pp" -exec awk -f ${BIN_DIR}/findparams.awk {} \;); do
+  HIERA_P_LIST[px]=$p
+  ((px++))
+done
+
+declare -r HIERA_LIST="$(for h in ${modulelist}; do grep -PIRho "(?<=hiera\(['|\"|$])([^'|^\"|^,|^\)]+)" ${h} | sort -u; done)"
+declare -r HIERA_A_LIST="$(for ha in ${modulelist}; do grep -PIRho "(?<=hiera_array\(['|\"|$])([^'|^\"|^,|^\)]+)" ${ha} | sort -u; done)"
+declare -r HIERA_H_LIST="$(for hh in ${modulelist}; do grep -PIRho "(?<=hiera_hash\(['|\"|$])([^'|^\"|^,|^\)]+)" ${hh} | sort -u; done)"
+declare -r HIERA_BASE_OPTS="-c ${HIERADIR}"
+declare -r HIERA="$(which hiera)"
+declare -r HIERA_BASE_CMD="${HIERA} ${HIERA_BASE_OPTS}"
+declare    HIERA_CMD="${HIERA_BASE_CMD} ${HIERA_EXTRA_OPTS}"
+
+for cert in ${CERTLIST_RAW}; do [ "${cert}" == "${cert/pe-internal-/}" ] && CERTLIST="${CERTLIST} ${cert}" ; done
+
+
+case "${fact_src}" in
+  'yaml' )
+    for node in ${CERTLIST}; do
+      if [ ! -f "${node}.yaml" ] ; then echo "Warning, could not find ${node}.yaml.  Skipping." ; continue 1 ; fi
+      echo "Looking up hiera() call values for ${node}."
+      for ch in ${HIERA_LIST} ; do echo "${ch} is $(${HIERA_CMD} ${FILE_BASE}/${node}.yaml ${ch})"; done
+      echo "Looking up hiera_array() call values for ${node}."
+      for cha in ${HIERA_A_LIST} ; do echo "${cha} is $(${HIERA_CMD} ${FILE_BASE}/${node}.yaml -a ${cha})"; done
+      echo "Looking up hiera_hash() call values for ${node}."
+      for chh in ${HIERA_H_LIST} ; do echo "${chh} is $(${HIERA_CMD} ${FILE_BASE}/${node}.yaml -h ${chh})"; done
+      echo "Looking up automatica paramater values for ${node}." 
+      for chp in ${HIERA_P_LIST[@]} ; do echo "${chp} is $(${HIERA_CMD} ${FILE_BASE}/${node}.yaml ${chp})"; done
+    done
+    ;;
+  'json' )
+    for node in ${CERTLIST}; do
+      if [ ! -f "${node}.json" ] ; then echo "Warning, could not find ${node}.json. Skipping." ; continue 1 ; fi
+      echo "Looking up hiera() call values for ${node}."
+      for ch in ${HIERA_LIST} ; do echo "${ch} is $(${HIERA_CMD} ${FILE_BASE}/${node}.json ${ch})"; done
+      echo "Looking up hiera_array() call values for ${node}."
+      for cha in ${HIERA_A_LIST} ; do echo "${cha} is $(${HIERA__CMD} ${FILE_BASE}/${node}.json  -a ${cha})"; done
+      echo "Looking up hiera_hash() call values for ${node}."
+      for chh in ${HIERA_H_LIST} ; do echo "${chh} is $(${HIERA_CMD} ${FILE_BASE}/${node}.json  -h ${chh})"; done
+      echo "Looking up automatica paramater values for ${node}."
+      for chp in ${HIERA_P_LIST} ; do echo "${chp} is $(${HIERA_CMD} ${FILE_BASE}/${node}.json ${cp})"; done
+    done
+    ;;
+  'user' )
+    HIERA_CMD="sudo -u ${USER_NAME} ${HIERA} ${hiera_extra_opts} ${HIERA_BASE_OPTS}"
+    grep -qF "${USER_NAME}" /etc/passwd || fail_sauce "User '${USER_NAME}' not found. Please check spelling. Exiting."
+    for node in ${CERTLIST}; do
+      echo "Looking up hiera() call values for ${node}."
+      for ch in ${HIERA_LIST} ; do echo "${ch} is $( ${HIERA_CMD} -m ${node} ${ch})"; done
+      echo "Looking up hiera_array() call values for ${node}."
+      for cha in ${HIERA_A_LIST} ; do echo "${cha} is $( ${HIERA_CMD} -a -m ${node} ${cha})"; done
+      echo "Looking up hiera_hash() call values for ${node}."
+      for chh in ${HIERA_H_LIST} ; do echo "${chh} is $( ${HIERA_CMD} -h -m ${node} ${chh})"; done
+      echo "Looking up automatica paramater values for ${node}."
+      for chp in ${HIERA_P_LIST[@]} ; do echo "${chp} is $(${HIERA_CMD} -m ${node} ${chp})"; done
+    done
+    ;;
+  * )
+    fail_sauce "Unknown fact source '${fact_src}'. Exiting."
+    ;;
+esac
+
 exit $E_OK
