Several changes.  Changed the arithmetic operation (()) to a test case to prevent a subshell and the use of math inside shell... which is always risky.  Added a fail_sauce function to print-and-quit for ease of use.  Added exit variables for ease of use.  Fixed a lot of if..else..fi with what I call else-less programming.  People have a (bad) habit of doing this:  if positive test ; then do positive thing ; else alert about negative thing ; fi.  This can be replaced with a much cleaner version:  if negative thing ; alert about negative thing ; fi <continue on with positive thing outside the if construct).  It's wayyyy cleaner to read IMO.  I also switched the big if..elif..elif...elif..fi construct to a case..esac strucutre.  If the if..elif stuff was intention for older versions of bash, sorry.

diff --git a/bin/glowing-octo-ninja b/bin/glowing-octo-ninja
--- a/bin/glowing-octo-ninja
+++ b/bin/glowing-octo-ninja
@@ -5,10 +5,11 @@
 #@Version   0.1.1
 #@Namespace friedbob_scripts
 
-__SBT_SHUTUP='true'
-__SBT_VERBOSE='false'
-
-BIN_DIR="$(dirname $(readlink -f "${BASH_SOURCE}"))"
+declare -r -i E_OK=0
+declare -r -i E_GENERIC_FAILURE=1
+declare       __SBT_SHUTUP='true'
+declare       __SBT_VERBOSE='false'
+declare -r    BIN_DIR="$(dirname $(readlink -f "${BASH_SOURCE}"))"
 . "${BIN_DIR}/../lib/sbt_libs.sh"
 
 # Create a function for usage... because the original multi-line variable scares me...
@@ -37,7 +38,14 @@ function usage {
         msg+="\nNote that only one of json, user or yaml can be specified."
 
   echo -e "${msg}"
-  return 0
+  return ${E_OK}
+}
+
+function fail_sauce {
+  # Wrapper to echo $* out (using $* to mash all words together).
+  echo -e "$*"
+  exit ${E_GENERIC_FAILURE}
+  return ${E_OK}  # This will never be hit.
 }
 
 #Need to determine the path for Puppet, rather than hardcoding the PE path
@@ -52,27 +60,26 @@ fi
 declare -r LONG_OPTS="help,yaml,user:,json,debug,filebase:"
 declare -r SHORT_OPTS="hyu:jdf:"
 declare -r FILE_BASE="."
+declare    fact_src="user"
 
-if (( $# == 0 )); then
-  fact_src="user"
-else
+if [ $# -gt 0 ]; then
   mutex_option='false'
   while core_getopts "${SHORT_OPTS}" opt "${LONG_OPTS}" "$@"; do
     case "${opt}" in
       h | help ) usage; exit 0;;
       f | filebase ) FILE_BASE="${OPTARG}";;
       u | user )
-        if ${mutex_option}; then echo "Please set only one of user, yaml or json options."; exit 1; fi
+        ${mutex_option} && fail_sauce "Please set only one of user, yaml or json options."
         mutex_option='true'
         fact_src="user"
         hiera_extra_opts="${hiera_extra_opts} -m";;
       y | yaml )
-        if ${mutex_option}; then echo "Please set only one of user, yaml or json options."; exit 1; fi
+        ${mutex_option} && fail_sauce "Please set only one of user, yaml or json options."
         mutex_option='true'
         fact_src="yaml"
         hiera_extra_opts="${hiera_extra_opts} -y ${OPTARG}";;
       j | json )
-        if ${mutex_option}; then echo "Please set only one of user, yaml or json options."; exit 1; fi
+        ${mutex_option} && fail_sauce "Please set only one of user, yaml or json options."
         mutex_option='true'
         fact_src="json"
         hiera_extra_opts="${hiera_extra_opts} -j" ;;
@@ -89,41 +96,34 @@ declare -r CONFIGDIR="$("${PUPPET_BIN}" config print confdir 2> /dev/null)"
 declare -r ENVIRONMENTPATH="$("${PUPPET_BIN}" config print environmentpath 2> /dev/null)"
 declare -r BASEMODULEPATH="$("${PUPPET_BIN}" config print basemodulepath 2> /dev/null)"
 
+# Assume directory environments are being used; we'll check for an empty $ENVIRONMENTPATH next and reset as-needed.
+mod_ep="${ENVIRONMENTPATH}"
+mod_bmp="${BASEMODULEPATH}"
+[[ ${ENVIRONMENTPATH} =~ '$confdir' ]] && mod_ep="${ENVIRONMENTPATH/'$confdir'/${CONFIGDIR}}"
+[[ ${BASEMODULEPATH} =~ '$confdir' ]]  && mod_bmp="${BASEMODULEPATH/'$confdir'/${CONFIGDIR}}"
+modulelist="${mod_ep} ${mod_bmp}"
+# -- This is our check for config directories in play, rather than directory environments.
 if [ "${ENVIRONMENTPATH}" == '']; then #config directories are in play
-  if grep -qe  "modulepath.*[$][::]\?environment" "${CONFIGDIR}/puppet.conf"; then # Dynamic Environments
+  modulelist="$("${PUPPET_BIN}" config print modulepath | sed -e "s/:/ /g")"       # Assume static config directory (overwriting from above).
+  if grep -qe  "modulepath.*[$][::]\?environment" "${CONFIGDIR}/puppet.conf"; then # Dynamic Environments, reset modulelist for compilation below.
     modulelist=""
-    for m in $(grep -P  '^[\s]*modulepath' "${CONFIGDIR}/puppet.conf" | cut -d'=' -f2 | awk 'BEGIN {RS = ":"} ; {print $0}')
-      do
-        if grep -P '\$(::)?environment' <<<"${m}" | grep -Po '^[$|/][a-zA-Z/]*'; then
-            if [[ "${m}" =~ '$confdir' ]]; then
-              kladsjhfiladhfklasjdfghldksj="$(echo ${m} | grep -Po '^[$|/][a-zA-Z/]*')"
-              modulelist="${modulelist} ${kladsjhfiladhfklasjdfghldksj/\$confdir/${CONFIGDIR}}"
-            else
-              modulelist="${modulelist} $(echo ${m} | grep -Po '^[$|/][a-zA-Z/]*')"
-            fi
+    for m in $(grep -P  '^[\s]*modulepath' "${CONFIGDIR}/puppet.conf" | cut -d'=' -f2 | awk 'BEGIN {RS = ":"} ; {print $0}') ; do
+      if grep -P '\$(::)?environment' <<<"${m}" | grep -Po '^[$|/][a-zA-Z/]*'; then
+        if [[ "${m}" =~ '$confdir' ]]; then
+          kladsjhfiladhfklasjdfghldksj="$(echo ${m} | grep -Po '^[$|/][a-zA-Z/]*')"
+          modulelist="${modulelist} ${kladsjhfiladhfklasjdfghldksj/\$confdir/${CONFIGDIR}}"
         else
-          if [[ "${m}" =~ '$confdir' ]]; then
-            modulelist="${modulelist} ${m/\$confdir/${CONFIGDIR}}"
-          else
-            modulelist="${modulelist} ${m}"
-          fi
+          modulelist="${modulelist} $(echo ${m} | grep -Po '^[$|/][a-zA-Z/]*')"
         fi
-      done
-  else #Static config directory
-    modulelist="$("${PUPPET_BIN}" config print modulepath | sed -e "s/:/ /g")"
+      else
+        if [[ "${m}" =~ '$confdir' ]]; then
+          modulelist="${modulelist} ${m/\$confdir/${CONFIGDIR}}"
+        else
+          modulelist="${modulelist} ${m}"
+        fi
+      fi
+    done
   fi
-else #Directory environments are being used
-  if [[ ${ENVIRONMENTPATH} =~ '$confdir' ]]; then
-    mod_ep="${ENVIRONMENTPATH/'$confdir'/${CONFIGDIR}}"
-  else
-    mod_ep="${ENVIRONMENTPATH}"
-  fi
-  if [[ ${BASEMODULEPATH} =~ '$confdir' ]]; then
-    mod_bmp="${BASEMODULEPATH/'$confdir'/${CONFIGDIR}}"
-  else
-    mod_bmp="${BASEMODULEPATH}"
-  fi
-  modulelist="${mod_ep} ${mod_bmp}"
 fi
 
 declare -r HIERADIR="$("${PUPPET_BIN}" config print hiera_config 2> /dev/null)"
@@ -139,52 +139,46 @@ declare -r HIERA="$(which hiera)"
 declare -r HIERA_BASE_CMD="${HIERA} ${HIERA_BASE_OPTS}"
 declare    HIERA_CMD="${HIERA_BASE_CMD} ${HIERA_EXTRA_OPTS}"
 
-for cert in ${CERTLIST_RAW}; do
-  if [ "${cert}" == "${cert/pe-internal-/}" ]; then CERTLIST="${CERTLIST} ${cert}"; fi
-done
+for cert in ${CERTLIST_RAW}; do [ "${cert}" == "${cert/pe-internal-/}" ] && CERTLIST="${CERTLIST} ${cert}" ; done
 
-if [ "${fact_src}" == 'yaml' ]; then
-  for node in ${CERTLIST}; do
-    if [ -f "${node}.yaml" ]; then
+case "${fact_src}" in
+  'yaml' )
+    for node in ${CERTLIST}; do
+      if [ ! -f "${node}.yaml" ] ; then echo "Warning, could not find ${node}.yaml.  Skipping." ; continue 1 ; fi
       echo "Looking up hiera() call values for ${node}."
       for ch in ${HIERA_LIST} ; do ${HIERA_CMD} "${FILE_BASE}/${node}.yaml" "${ch}"; done
       echo "Looking up hiera_array() call values for ${node}."
       for cha in ${HIERA_A_LIST} ; do ${HIERA_CMD} "${FILE_BASE}/${node}.yaml" -a "${cha}"; done
       echo "Looking up hiera_hash() call values for ${node}."
       for chh in ${HIERA_H_LIST} ; do ${HIERA_BASE_CMD} "${FILE_BASE}/${node}.yaml" -h "${chh}"; done
-    else
-      echo "Warning, could not find ${node}.yaml. Skipping."
-    fi
-  done
-elif [ "${fact_src}" == 'json' ]; then
-  for node in ${CERTLIST}; do
-    if [ -f "${node}.json" ]; then
+    done
+    ;;
+  'json' )
+    for node in ${CERTLIST}; do
+      if [ ! -f "${node}.json" ] ; then echo "Warning, could not find ${node}.json. Skipping." ; continue 1 ; fi
       echo "Looking up hiera() call values for ${node}."
       for ch in ${HIERA_LIST} ; do ${HIERA_CMD} "${FILE_BASE}/${node}.json" "${ch}"; done
       echo "Looking up hiera_array() call values for ${node}."
       for cha in ${HIERA_A_LIST} ; do ${HIERA__CMD} "${FILE_BASE}/${node}.json" -a "${cha}"; done
       echo "Looking up hiera_hash() call values for ${node}."
       for chh in ${HIERA_H_LIST} ; do ${HIERA_BASE_CMD} "${FILE_BASE}/${node}.json" -h "${chh}"; done
-    else
-      echo "Warning, could not find ${node}.json. Skipping."
-    fi
-  done
-elif [ "${fact_src}" == 'user' ]; then
-  if $(grep -qF "${USER_NAME}" /etc/passwd); then
+    done
+    ;;
+  'user' )
     HIERA_CMD="sudo -u ${USER_NAME} ${HIERA} ${hiera_extra_opts} ${HIERA_BASE_OPTS}"
-  else
-    echo "User '${USER_NAME}' not found. Please check spelling. Exiting."
-    exit 1
-  fi
-  for node in ${CERTLIST}; do
-    echo "Looking up hiera() call values for ${node}."
-    for ch in ${HIERA_LIST} ; do echo "${ch} is $( ${HIERA_CMD} -m "${node}" "${ch}")"; done
-    echo "Looking up hiera_array() call values for ${node}."
-    for cha in ${HIERA_A_LIST} ; do echo "${cha} is $( ${HIERA_CMD} -a -m "${node}" "${cha}")"; done
-    echo "Looking up hiera_hash() call values for ${node}."
-    for chh in ${HIERA_H_LIST} ; do echo "${chh} is $( ${HIERA_CMD} -h -m "${node}" "${chh}")"; done
-  done
-else
-  echo "Unknown fact source. Exiting."
-  exit 1
-fi
+    grep -qF "${USER_NAME}" /etc/passwd || fail_sauce "User '${USER_NAME}' not found. Please check spelling. Exiting."
+    for node in ${CERTLIST}; do
+      echo "Looking up hiera() call values for ${node}."
+      for ch in ${HIERA_LIST} ; do echo "${ch} is $( ${HIERA_CMD} -m "${node}" "${ch}")"; done
+      echo "Looking up hiera_array() call values for ${node}."
+      for cha in ${HIERA_A_LIST} ; do echo "${cha} is $( ${HIERA_CMD} -a -m "${node}" "${cha}")"; done
+      echo "Looking up hiera_hash() call values for ${node}."
+      for chh in ${HIERA_H_LIST} ; do echo "${chh} is $( ${HIERA_CMD} -h -m "${node}" "${chh}")"; done
+    done
+    ;;
+  * )
+    fail_sauce "Unknown fact source '${fact_src}'. Exiting."
+    ;;
+esac
+
+exit $E_OK
